<%@ Page Title="College Education System | Notifications" Language="C#" MasterPageFile="~/MasterPages/Main.Master" AutoEventWireup="true" CodeBehind="Show_Notification.aspx.cs" Inherits="CollegeEducationFileSystem.Forms.Show_Notification" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
                    <link href="../Stylesheets/Grids.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <h2>Notifications</h2>
            <div class="container">
                <asp:GridView CssClass="girdss" ID="Notification_Admin" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateColumns="False" DataKeyNames="notificationid" DataSourceID="Admin_Source" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775"></AlternatingRowStyle>

                    <Columns>
                        <asp:BoundField DataField="notificationid" HeaderText="notificationid" ReadOnly="True" InsertVisible="False" SortExpression="notificationid"></asp:BoundField>
                        <asp:BoundField DataField="title" HeaderText="title" SortExpression="title"></asp:BoundField>
                        <asp:BoundField DataField="summary" HeaderText="summary" SortExpression="summary"></asp:BoundField>
                        <asp:BoundField DataField="date" HeaderText="date" SortExpression="date"></asp:BoundField>
                    </Columns>

                    <EditRowStyle BackColor="#999999"></EditRowStyle>

                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White"></FooterStyle>

                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White"></HeaderStyle>

                    <PagerStyle HorizontalAlign="Center" BackColor="#284775" ForeColor="White"></PagerStyle>

                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333"></RowStyle>

                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333"></SelectedRowStyle>

                    <SortedAscendingCellStyle BackColor="#E9E7E2"></SortedAscendingCellStyle>

                    <SortedAscendingHeaderStyle BackColor="#506C8C"></SortedAscendingHeaderStyle>

                    <SortedDescendingCellStyle BackColor="#FFFDF8"></SortedDescendingCellStyle>

                    <SortedDescendingHeaderStyle BackColor="#6F8DAE"></SortedDescendingHeaderStyle>
                </asp:GridView>

                <asp:SqlDataSource runat="server" ID="Admin_Source" ConnectionString='<%$ ConnectionStrings:DBCS %>' DeleteCommand="DELETE FROM [Notification] WHERE [notificationid] = @notificationid" InsertCommand="INSERT INTO [Notification] ([title], [summary], [date]) VALUES (@title, @summary, @date)" SelectCommand="SELECT * FROM [Notification]" UpdateCommand="UPDATE [Notification] SET [title] = @title, [summary] = @summary, [date] = @date WHERE [notificationid] = @notificationid">
                    <DeleteParameters>
                        <asp:Parameter Name="notificationid" Type="Int32"></asp:Parameter>
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="title" Type="String"></asp:Parameter>
                        <asp:Parameter Name="summary" Type="String"></asp:Parameter>
                        <asp:Parameter DbType="Date" Name="date"></asp:Parameter>
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="title" Type="String"></asp:Parameter>
                        <asp:Parameter Name="summary" Type="String"></asp:Parameter>
                        <asp:Parameter DbType="Date" Name="date"></asp:Parameter>
                        <asp:Parameter Name="notificationid" Type="Int32"></asp:Parameter>
                    </UpdateParameters>
                </asp:SqlDataSource>
            </div>


            <div class="container">

                <asp:GridView CssClass="girdss" ID="Ord_Notification_Grid" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateColumns="False" DataSourceID="Ord_Source">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775"></AlternatingRowStyle>

                    <Columns>
                        <asp:BoundField DataField="title" HeaderText="title" SortExpression="title"></asp:BoundField>
                        <asp:BoundField DataField="summary" HeaderText="summary" SortExpression="summary"></asp:BoundField>
                        <asp:BoundField DataField="date" HeaderText="date" SortExpression="date"></asp:BoundField>
                    </Columns>

                    <EditRowStyle BackColor="#999999"></EditRowStyle>

                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White"></FooterStyle>

                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White"></HeaderStyle>

                    <PagerStyle HorizontalAlign="Center" BackColor="#284775" ForeColor="White"></PagerStyle>

                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333"></RowStyle>

                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333"></SelectedRowStyle>

                    <SortedAscendingCellStyle BackColor="#E9E7E2"></SortedAscendingCellStyle>

                    <SortedAscendingHeaderStyle BackColor="#506C8C"></SortedAscendingHeaderStyle>

                    <SortedDescendingCellStyle BackColor="#FFFDF8"></SortedDescendingCellStyle>

                    <SortedDescendingHeaderStyle BackColor="#6F8DAE"></SortedDescendingHeaderStyle>
                </asp:GridView>
                <asp:SqlDataSource runat="server" ID="Ord_Source" ConnectionString='<%$ ConnectionStrings:DBCS %>' SelectCommand="SELECT [title], [summary], [date] FROM [Notification]"></asp:SqlDataSource>
            </div>
    </div>
</asp:Content>
