<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPages/Main.Master" AutoEventWireup="true" CodeBehind="Show_Applications.aspx.cs" Inherits="CollegeEducationFileSystem.Forms.Show_Applications" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
        <link href="../Stylesheets/Grids.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
                <h2>Applications </h2>
        <asp:Button CssClass="Button2" ID="PEND" runat="server" Text="Pending"  ValidationGroup="be" Visible="False" OnClick="PEND_Click" /><asp:Button CssClass="Button2" ID="REC" runat="server" Text="Approved" ValidationGroup="be" Visible="False" OnClick="REC_Click" />
    </div>
    <div class="container">
        <asp:GridView ID="Admin_B" CssClass="girdss" runat="server" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="appid" DataSourceID="Admin_Pend_Source" ForeColor="#333333" GridLines="None" OnRowCommand="Apprve_App" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Visible="False">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="appid" HeaderText="appid" InsertVisible="False" ReadOnly="True" SortExpression="appid" />
                <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
                <asp:BoundField DataField="reason" HeaderText="reason" SortExpression="reason" />
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="status" HeaderText="status" SortExpression="status" />
                <asp:ButtonField ControlStyle-CssClass="Button" CommandName="aproov" HeaderText="Action" Text="Approve" ButtonType="Button" >
<ControlStyle CssClass="Button"></ControlStyle>
                </asp:ButtonField>
                <asp:ButtonField ButtonType="Button" CommandName="Rejection" HeaderText="Actions" Text="Reject" ControlStyle-CssClass="Button"/>
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>

        <asp:SqlDataSource ID="Admin_Pend_Source" runat="server" ConnectionString="<%$ ConnectionStrings:DBCS %>" DeleteCommand="DELETE FROM [Applications] WHERE [appid] = @appid" InsertCommand="INSERT INTO [Applications] ([title], [reason], [name], [status]) VALUES (@title, @reason, @name, @status)" SelectCommand="SELECT * FROM [Applications]" UpdateCommand="UPDATE [Applications] SET [title] = @title, [reason] = @reason, [name] = @name, [status] = @status WHERE [appid] = @appid">
            <DeleteParameters>
                <asp:Parameter Name="appid" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="title" Type="String" />
                <asp:Parameter Name="reason" Type="String" />
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="status" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="title" Type="String" />
                <asp:Parameter Name="reason" Type="String" />
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="status" Type="String" />
                <asp:Parameter Name="appid" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>


        <asp:GridView  CssClass="girdss" ID="Admin_Apd" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="appid" DataSourceID="Admin_Apprvd_Source" ForeColor="#333333" GridLines="None" Visible="False">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="appid" HeaderText="appid" InsertVisible="False" ReadOnly="True" SortExpression="appid" />
                <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
                <asp:BoundField DataField="reason" HeaderText="reason" SortExpression="reason" />
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="status" HeaderText="status" SortExpression="status" />
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>



        <asp:SqlDataSource ID="Admin_Apprvd_Source" runat="server" ConnectionString="<%$ ConnectionStrings:DBCS %>" DeleteCommand="DELETE FROM [Applications] WHERE [appid] = @appid" InsertCommand="INSERT INTO [Applications] ([title], [reason], [name], [status]) VALUES (@title, @reason, @name, @status)" SelectCommand="SELECT * FROM [Applications] where status='Approved'" UpdateCommand="UPDATE [Applications] SET [title] = @title, [reason] = @reason, [name] = @name, [status] = @status WHERE [appid] = @appid">
            <DeleteParameters>
                <asp:Parameter Name="appid" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="title" Type="String" />
                <asp:Parameter Name="reason" Type="String" />
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="status" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="title" Type="String" />
                <asp:Parameter Name="reason" Type="String" />
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="status" Type="String" />
                <asp:Parameter Name="appid" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>


    <asp:GridView CssClass="girdss" ID="Ordinary_Grid" runat="server" AutoGenerateColumns="False" CellPadding="4" DataSourceID="Ord_Source" ForeColor="#333333" GridLines="None">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
            <asp:BoundField DataField="reason" HeaderText="reason" SortExpression="reason" />
            <asp:BoundField DataField="status" HeaderText="status" SortExpression="status" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>
    <asp:SqlDataSource ID="Ord_Source" runat="server" ConnectionString="<%$ ConnectionStrings:DBCS %>" SelectCommand="SELECT [title], [reason], [status] FROM [Applications] where name = @name"> <SelectParameters><asp:SessionParameter Name="name" SessionField="Name" /></SelectParameters> </asp:SqlDataSource>
</asp:Content>
