<%@ Page Title="College Education System | Show Payments" Language="C#" MasterPageFile="~/MasterPages/Main.Master" AutoEventWireup="true" CodeBehind="Show_Payments.aspx.cs" Inherits="CollegeEducationFileSystem.Forms.Show_Payments" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
                <link href="../Stylesheets/Grids.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <h2>Payments </h2>
    <asp:GridView CssClass="girdss" ID="Admin_Grids" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="paymentid" DataSourceID="Admin_Source" ForeColor="#333333" GridLines="None">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="paymentid" HeaderText="paymentid" InsertVisible="False" ReadOnly="True" SortExpression="paymentid" />
            <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
            <asp:BoundField DataField="ammount" HeaderText="ammount" SortExpression="ammount" />
            <asp:BoundField DataField="studentname" HeaderText="studentname" SortExpression="studentname" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>
    <asp:SqlDataSource ID="Admin_Source" runat="server" ConnectionString="<%$ ConnectionStrings:DBCS %>" DeleteCommand="DELETE FROM [Payments] WHERE [paymentid] = @paymentid" InsertCommand="INSERT INTO [Payments] ([title], [ammount], [studentname]) VALUES (@title, @ammount, @studentname)" SelectCommand="SELECT * FROM [Payments]" UpdateCommand="UPDATE [Payments] SET [title] = @title, [ammount] = @ammount, [studentname] = @studentname WHERE [paymentid] = @paymentid">
        <DeleteParameters>
            <asp:Parameter Name="paymentid" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="title" Type="String" />
            <asp:Parameter Name="ammount" Type="Int32" />
            <asp:Parameter Name="studentname" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="title" Type="String" />
            <asp:Parameter Name="ammount" Type="Int32" />
            <asp:Parameter Name="studentname" Type="String" />
            <asp:Parameter Name="paymentid" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>



        <asp:GridView CssClass="girdss" ID="Student_Gridsss" runat="server" AutoGenerateColumns="False" CellPadding="4" DataSourceID="Student_Sources" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
                <asp:BoundField DataField="ammount" HeaderText="ammount" SortExpression="ammount" />
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>


        <asp:SqlDataSource ID="Student_Sources" runat="server" ConnectionString="<%$ ConnectionStrings:DBCS %>" SelectCommand="SELECT [title], [ammount] FROM [Payments] where studentname= @name"> <SelectParameters> <asp:SessionParameter Name="name" SessionField="Name" />   </SelectParameters> </asp:SqlDataSource>


        </div>
</asp:Content>
